#!/bin/sh

if [ $# -eq 0 -o "$1" = "--help" ]; then
  echo "USAGE: $0 filename [filename ...]"
  exit 1
fi

for FILE in "$*"; do
  # https://bugs.launchpad.net/ubuntu/+source/ttf-freefont/+bug/447961
  #sed -e 's/^/              /' "${FILE}" | lp -o cpi=16.5 -o lpi=6
  sed -e 's/^/       /' "${FILE}" | lp
done
