#!/bin/sh

if [ $# -ne 1 -o "$1" = "--help" ]; then
  echo "USAGE: $0 filename"
  exit 1
fi

# https://bugs.launchpad.net/ubuntu/+source/ttf-freefont/+bug/447961
#sed -e 's/^/              /' $1 | lp -o cpi=16.5 -o lpi=6
sed -e 's/^/       /' $1 | lp
